sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
git:
  submodules: false

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 3.8
      env: TOXENV=py38
      dist: bionic
      sudo: true
    - python: 3.9
      env: TOXENV=py39
      dist: focal
      sudo: true
    - python: 'nightly'
      env: TOXENV=py310
      dist: focal
      sudo: true
  allow_failures:
    - python: nightly

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
    - pip install -r requirements-dev.txt

script:
    - tox -e $TOXENV
